### ISSUE TITLE
updated?

### ISSUE THREAD

**Issue by bobbler321** [zyhp/vac3_inhibitor#12] opened 2021-03-12 20:06 UTC
I know there were some "unknown modules" but as I was messing around with it I noticed that there were no [ VAC3 ] notifications in the console. I also get "vac unable to verify game session". I'm wondering if this is outdated or if I'm just retarded keep in mind I know jack shit about coding.

**Comment by blxckshark** [comment] 2021-04-01 22:58
> I know there were some "unknown modules" but as I was messing around with it I noticed that there were no [ VAC3 ] notifications in the console. I also get "vac unable to verify game session". I'm wondering if this is outdated or if I'm just retarded keep in mind I know jack shit about coding.

Some news, does it works?

**Comment by bobbler321** [comment] 2021-04-01 23:01
¯\_(ツ)_/¯ I just started using the other vac bypass until a new pull request is made, just to be on the safe side

**Comment by blxckshark** [comment] 2021-04-01 23:22
> ¯_(ツ)_/¯ I just started using the other vac bypass until a new pull request is made, just to be on the safe side

link please?

**Comment by bobbler321** [comment] 2021-04-01 23:24
> > ¯_(ツ)_/¯ I just started using the other vac bypass until a new pull request is made, just to be on the safe side
> 
> link please?
> And actually, this shit is outdated, we need new patterns.

https://github.com/danielkrupinski/VAC-Bypass

**Comment by zyhp** [comment] 2021-04-04 20:37
Duplicate of #10

**Closed by zyhp** 2021-04-04 20:37 UTC
